package com.tommasoberlose.anotherwidget.global

enum class RequestCode(val code: Int) {
    CALENDAR_REQUEST_CODE(1),
    LOCATION_REQUEST_CODE(2),
    CALENDAR_APP_REQUEST_CODE(3),
    WEATHER_APP_REQUEST_CODE(4),
    EVENT_APP_REQUEST_CODE(6),
    WEATHER_PROVIDER_REQUEST_CODE(5),
    CLOCK_APP_REQUEST_CODE(7),
    CUSTOM_FONT_CHOOSER_REQUEST_CODE(8)
}